### ISSUE TITLE
Update to webpack 4

### ISSUE THREAD

**Issue by crucialfelix** [Plant-for-the-Planet-org/treecounter-app#1320]
It caches compiled results. Build time and hot reload is much faster.

https://webpack.js.org/migrate/4/

Many of the loaders need to be upgraded and checked as well.

**Comment by norbertschuler** [comment]
I would like to start this project after release of version 1.1 in October together with these issues:
- CSS/JS versioning https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1250 instead of this (never implemented) issue https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1252
- image optimization https://github.com/Plant-for-the-Planet-org/treecounter-app/issues/1430
