### ISSUE TITLE
Blank screen with error 401 loading TTC

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#1477]
## Error in Plant-for-the-Planet App

**Error** in **/**
Request failed with status code 401

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8ccfc89610940019a19cb9?event_id=5d8ccfc80050434220de0000&i=gh&m=ci)

## Stacktrace

    http://0.0.0.0:8080/bundle.js:36160 - createError

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5d8ccfc89610940019a19cb9?event_id=5d8ccfc80050434220de0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Sometimes when I am testing I failed to load the app (happens in web client and in native apps). I recognized I get a 401 error then for authentication but the app doesn’t show me the login again, but just stopped and therefore showing a blank screen until I reload. Then I get a login screen and can use it again.

**Comment by norbertschuler** [comment]
<img width="877" alt="Bildschirmfoto 2019-09-30 um 18 59 03" src="https://user-images.githubusercontent.com/1532418/65899634-6d5de800-e3b4-11e9-94ee-f726d960acbf.png">

**Comment by sagararyal** [comment]
@norbertschuler is it possible due to rate limiting?

**Comment by norbertschuler** [comment]
No, I don’t think that’s the problem here. But if you experience it, look in our Slack channel `notifications-rate-limit` if you see your IP in the latest message.

**Comment by norbertschuler** [comment]
I think this always happens if you are logged in with the app and the web client at the same time. (Or maybe just with two clients at the same time.) Then the refresh token of the older client is not accepted any more by the backend throwing at 400 error and afterwards the other API calls using a token are throwing 401 errors:

<img width="571" alt="Bildschirmfoto 2019-10-11 um 14 11 18" src="https://user-images.githubusercontent.com/1532418/66650488-069cc200-ec31-11e9-8163-d8d225ec2ad6.png">

**Comment by norbertschuler** [comment]
code: 401

**Comment by norbertschuler** [comment]
This error wasn't solved just by catching errors from promises (I already thought that), so I have to open it again:
<img width="895" alt="Bildschirmfoto 2019-10-16 um 14 50 41" src="https://user-images.githubusercontent.com/1532418/66920811-5827c100-f024-11e9-87e6-7cb0bb46eb7b.png">
