### ISSUE TITLE
Donate Trees : release candidate v1.2

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1670]
- [x] In Single Projects Page, the price doesn't work property, so implement a floating button.
- [x] In project list view target, comma is missing on number less than 100k eg (100,000)
- [x] Fix Donation view, when support is being clicked, Instead of bring users to Donate trees without option to go back

**Comment by mahmed0715** [comment]
@sagararyal `In Single Projects Page, the price doesn't work property, so implement a floating button.` need explanation please

**Comment by sagararyal** [comment]
@mahmed0715 
the price per tree needs to be tapped twice to go to the donate screen,

instead of fixing that, which will be removed in future updates, you could have the Donate button, which is at the bottom of the screen be a floating button, like it is in Edit Competition and other places.

this will be removed in future as well.

**Comment by mahmed0715** [comment]
on it.

**Comment by norbertschuler** [comment]
@sagararyal check out this floating donate button @mahmed0715 has build:

![Simulator Screen Shot - iPhone 11 - 2019-12-06 at 15 35 52](https://user-images.githubusercontent.com/1532418/70330589-266df200-183e-11ea-9107-6262efafce1b.png)

**Comment by mahmed0715** [comment]
@norbertschuler the background texts are scrollable, right?
 so all the contents behind the button are visible if scrolled. right?
