### ISSUE TITLE
Not able to configure environment for testing.

### ISSUE THREAD

**Issue by enroot-mumbai** [Plant-for-the-Planet-org/treecounter-app#1679]
Error while trying to run test file.

I was trying to test the pledgeActions.js file but keep getting the error attached in the image.

![jest-config-error](https://user-images.githubusercontent.com/44316146/69855552-beedfa80-12b1-11ea-9b8e-8e2073d4501b.JPG)

**Comment by dileshtanna** [comment]
I am getting this problem while running tests. When a react native project is created, jest is already configured to use Babel. However, it is unable to use Babel. I tried configuring Jest to use transforms and presets but it is still not working. What I believe is happening is that some configuration is overriding the Jest configuration due to which tests are failing. One interesting thing that happened was that when I tried using require statements instead of imports, I faced the same issue. Is anyone else running the same issue?

Steps to reproduce :
Install Jest and run jest. It will automatically detect the App-test.js file
Next, configure testUrl to http://localhost to solve the security problem for localstorage that arises when you run the tests.
It will show an error at '<' in the test file where the App component is used.

**Comment by norbertschuler** [comment]
Thank you for adding this issue. I tried adding support for jest, but unfortunately did not succeed as still experiences an error in #1680. Maybe after migrating to react-native 0.6x we can try again solving this issue.

**Comment by norbertschuler** [comment]
I tried various version of the `jest` and `babel-jest` libraries, but none was working. I looked at the source code of `node_modules/jest/node_modules/jest-resolve/build/index.js` and `node_modules/react-native/Libraries/react-native/react-native-implementation.js` to find out why `warnOnce` could not be found (it was moved from react-native 0.58 to 0.59 in another folder). Now I think the problem could also be found with the current react-native version not working with jest. I would like to test if jest works when we successfully upgrade to react-native 0.6x. as I don't want to waste another day in trying to find a working combination of libraries for the current setup :-(

**Comment by dileshtanna** [comment]
> I tried various versions of the `jest` and `babel-jest` libraries, but none was working. I looked at the source code of `node_modules/jest/node_modules/jest-resolve/build/index.js` and `node_modules/react-native/Libraries/react-native/react-native-implementation.js` to find out why `warnOnce` could not be found (it was moved from react-native 0.58 to 0.59 in another folder). Now I think the problem could also be found with the current react-native version not working with jest. I would like to test if jest works when we successfully upgrade to react-native 0.6x. as I don't want to waste another day in trying to find a working combination of libraries for the current setup :-(

I tried updating the RN version. Still facing the same issues. Also, this problem does not arise in any other projects with this version of RN. I am guessing it is a conflict of configurations in the application. I am new to this app but I think someone working on this for some time would be able to find out the conflict (if it exists).

**Comment by norbertschuler** [comment]
I managed to make jest work in the pull request #1706 - but I can not render our base component `<App />` or other bigger components as I constantly get in trouble with some node modules which probably have to get mocked as the examples I already mocked. This would be some more effort to do.
