### ISSUE TITLE
While app loads, called api with undefined

### ISSUE THREAD

**Issue by mahmed0715** [Plant-for-the-Planet-org/treecounter-app#1681]
![Screenshot from 2019-11-29 18-15-27](https://user-images.githubusercontent.com/2967789/69868579-49dfec80-12d4-11ea-90ff-58bc904fa75c.png)
Brief description
When android app loading, see the api calls for first 1/2 api calls, language is undefined. 

OS: Android

Branch: Develop branch

**Comment by norbertschuler** [comment]
I can confirm this. It also happens for the `/loadTpos` API call as both get loaded at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/accd1f4cf0cc4f79e457f4df5dc90c50ff522a23/app/components/App/TreeCounter.native.js#L18 while the language is not yet determined because the loading if the `locale` is done asynchronously for the native app at https://github.com/Plant-for-the-Planet-org/treecounter-app/blob/accd1f4cf0cc4f79e457f4df5dc90c50ff522a23/app/actions/getLocale.native.js#L16
I experience putting the initLocale() in the constructor of the module, but it still wasn't fast enough and I did not solve this issue.
