### ISSUE TITLE
PledgeEvents v1.2

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1685]
- [ ] Add validation in the pledge Increment screen
- [ ] Currently it is possible to reduce pledges, api returns error but app does not react.
- [ ] Show all details in the Pledge Increment Screen
(allow user to change name or toggle anonymous status, disable email field)
- [x] Fix headers, remove title, and remove spacing 
- [ ] Refresh the page after pledge is updated (including the total pledged tree count)

**Comment by harshvitra** [comment]
@jmiridis 
`allow user to change name or toggle anonymous status, disable email field`

Need an Edit Pledge API which can allow the user to edit these fields 
1. First Name
2. Last Name
3. Email
4. Tree Count
5. Is Anonymous Status

**Comment by harshvitra** [comment]
Hey @norbertschuler  can you explain these issues 


Is number 1 and 2 the same or different ? 

Fix headers, remove titles, and remove spacing - Need more ideas on this ?
 
Refresh the page - Which page ? In the app or website ? Mostly I’m guessing Pledge Events screen on App.

**Comment by norbertschuler** [comment]
Discussion done in Slack (just to inform any possible reader here).

**Comment by harshvitra** [comment]
**For others to be clear**

- Add validation in the pledge Increment screen
- Currently it is possible to reduce pledges, api returns error but app does not react.

These are listed as 2 different but are the same
-------------------------------------------------------------------------------------------

-  Show all details in the Pledge Increment Screen (allow user to change name or toggle anonymous status, disable email field)

So user can change everything and NOT change email
-------------------------------------------------------------------------------------------

- Fix headers, remove title, and remove spacing ###DONE


Fixing - Removing Search icon, changing color 
Remove title - removing titles and adding them in header
Remove spacing - unnecessary
-------------------------------------------------------------------------------------------

-  Refresh the page after pledge is updated (including the total pledged tree count) 

This still needs to be tested and replicated
Cannot test since I cant create Pledges as of now due to error

**Comment by harshvitra** [comment]
@jmiridis can we fix #1692

we cannot solve other issues until this one is fixed

**Comment by norbertschuler** [comment]
> @jmiridis can we fix #1692
> 
> we cannot solve other issues until this one is fixed

Problem got fixed says @jmiridis.
