### ISSUE TITLE
SyntaxError in /gift-trees - expected expression, got '<'

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/treecounter-app#2163]
## Error in Plant-for-the-Planet App

**SyntaxError** in **/gift-trees**
expected expression, got '<'

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8b619167be77001711e8eb?event_id=5e8b6191005998a0ec710000&i=gh&m=ci)

## Stacktrace

    https://www.trilliontreecampaign.org/14.f414461c83a17966105e.js:1 - onerror

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e8b619167be77001711e8eb?event_id=5e8b6191005998a0ec710000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by norbertschuler** [comment]
Before this we always kept old files on the production system and copied the new files into the same web folder. Now we remove all old files before. Seems like some users still have the old version (we released 1.3.2 three times with different hashed file names) installed. Maybe we should purge the cache of Cloudflare, but we cannot purge the browser cache of our users.

**Comment by norbertschuler** [comment]
Result of `ChunkLoadError` - we cannot influence this right now except reduce the caching time for our client files.

**Comment by norbertschuler** [comment]
@sagararyal do you think we can or should further influence the caching in the user browsers for our client files - otherwise we have to just ignore these errors. (Please read the two comments above to understand the problem.) Having a shorter caching of the client files reduce errors for new deployment, but maybe gives the users a worse performance as loading our big client files too often makes the performance for our users slow.

**Comment by norbertschuler** [comment]
igoring this issues now
