### ISSUE TITLE
Explore - Sorting and filtering by drop down does not work

### ISSUE THREAD

**Issue by himpatel** [Plant-for-the-Planet-org/treecounter-app#217]
Explore page - Sorting or filtering by both the drop downs don't work. Nothing gets logged in the Nwtwork tab of the browser.

![image](https://user-images.githubusercontent.com/15386655/42308900-bca18ee0-8054-11e8-9694-a9294602ca05.png)

**Comment by norbertschuler** [comment]
It's true the result of e.g. the individual leadership board does not differ for the chosen time period, but is it because of an error or just because of the data just didn't change since all that time?
@jmiridis can you check this example please?

1. https://www.trilliontreecampaign.org/public/v1.1/de/exploreQuery/individual?orderBy=planted&period=all
2. https://www.trilliontreecampaign.org/public/v1.1/de/exploreQuery/individual?orderBy=planted&period=1-year
3. https://www.trilliontreecampaign.org/public/v1.1/de/exploreQuery/individual?orderBy=planted&period=5-years

**Comment by sagararyal** [comment]
@haideralishah can you fix this to use 1 week and 1 year just like in the mobile app.

**Comment by haideralishah** [comment]
Time period keys returning from the response are invalid.
![image](https://user-images.githubusercontent.com/9020813/74627742-99b4ae00-5175-11ea-94ba-8cf23f7ca2a7.png)
Currently, we using 3 filters in mobile app 
1) this week = `1w`
2) 1 year = `1y`
3) All time = `all`

so the query should be 
=>for 1 week 
 `https://test.trilliontreecampaign.org/public/v1.1/en/exploreQuery/company?orderBy=planted&period=1w`

=>for 1 Year 
 `https://test.trilliontreecampaign.org/public/v1.1/en/exploreQuery/company?orderBy=planted&period=1y`

=> for All Time 
  `https://test.trilliontreecampaign.org/public/v1.1/en/exploreQuery/company?orderBy=planted&period=all`

**Comment by haideralishah** [comment]
> @haideralishah can you fix this to use 1 week and 1 year just like in the mobile app.

fixed
