### ISSUE TITLE
Plant-for-the-plant treecounter does not show projects

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#2377]
**Describe the bug**
I can not see the projects of the Plant-for-the-Planet TPO any more looking at the treecounter https://www.trilliontreecampaign.org/t/plant-for-the-planet - other projects still show the projects, e.g. https://www.trilliontreecampaign.org/t/eden-reforestation-projects

Update: this of course also happens in the native apps!

**Is it on a Production or Development Build?**
production and develop

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/t/plant-for-the-planet

**Expected behavior**
Show the projects of the TPO underneath the treecounter.

**What actually happens**
Just showing the treecounter.

**Screenshots**
<img width="453" alt="Bildschirmfoto 2020-05-30 um 12 06 09" src="https://user-images.githubusercontent.com/1532418/83320066-17588180-a26e-11ea-9925-b53fa1a9894f.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser latest Chrome
- Plant-for-the-Planet App Version 1.3.3

**Comment by sanjayradadiya** [comment]
@jmiridis can you please check this api Request URL: https://app-development.plant-for-the-planet.org/public/v1.1/en/treecounter/ayudh-europe

![image](https://user-images.githubusercontent.com/16476120/83500066-ea110b00-a4db-11ea-9781-f1b7f9da1247.png)

Above api sending `userProfile.plantProjects` in array of object 

while Request URL: https://app-development.plant-for-the-planet.org/public/v1.1/en/treecounter/plant-for-the-planet
`userProfile.plantProjects` in object

![image](https://user-images.githubusercontent.com/16476120/83500007-dbc2ef00-a4db-11ea-95c9-340c714112f4.png)

let me know if this is expected behaviour

**Comment by norbertschuler** [comment]
@jmiridis Or compare https://app.plant-for-the-planet.org/public/v1.1/en/treecounter/weforest with https://app.plant-for-the-planet.org/public/v1.1/en/treecounter/plant-for-the-planet which both have multiple projects once returns as a key/value list of objects and once as an array.

**Comment by jmiridis** [comment]
@sanjayradadiya @norbertschuler Is it correct to assume that the expected response is an array and not an object?

**Comment by norbertschuler** [comment]
@jmiridis the Array currently works, so yes!

**Comment by jmiridis** [comment]
Fixed in release: https://github.com/Plant-for-the-Planet-org/treecounter-platform/releases/tag/20200606
